version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    environment:
      - DEBUG=True
    networks:
      - beam_test_backend

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - beam_test_backend

networks:
  beam_test_backend:
    driver: bridge
